site_name: IM Fagboka
site_url: https://docs.iktim.no
site_author: Sondre Grønås
site_description: >-
    En åpen digital fagbok for Informasjonsteknologi og Medieproduksjon ved Vågen VGS
docs_dir: docs

repo_name: docs.iktim.no
repo_url: https://github.com/VaagenIM/docs.iktim.no
edit_uri: edit/main/docs/

copyright: >
  Copyright &copy; 2021 - 2023 Sondre Grønås –
  <a href="#__consent">Endre personvernsinnstillinger</a>

theme:
    name: material
    custom_dir: overrides
    language: 'no'
    
    palette:  # Light/Dark Mode
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light mode

    features:
        - content.code.annotate     # Add annotations to codeblocks (```code (1)``` 1. annotation)
        - navigation.indexes        # Attach index.md to parent
        - navigation.tabs           # Subdirectories of docs/ as tabs
        - navigation.tracking       # Automatically add #anchor to URL while scrolling
        - navigation.top            # Back to top button
        - navigation.prune          # Performance / size optimization
        - search.suggest            # Autocomplete results during search
        - search.highlight          # Highlight occurences inside clicked search result
        - search.share              # Share search URL button in text input

    logo: logo.png
    favicon: https://iktim.no/favicon.ico


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sondregronas
      name: "@sondregronas"
    - icon: fontawesome/solid/paper-plane
      link: mailto:mail@iktim.no
  alternate:
    - name: Norsk
      link: '%GT_RELATIVE_URL%'
      lang: 'no'
    - name: English
      link: 'https://translate.goog/?_x_tr_sl=no&_x_tr_tl=en'
      lang: 'en'
  analytics:
    provider: google
    property: G-SRDC6RDQ19
    feedback:
      title: Var siden nyttig?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Siden var nyttig
          data: 1
          note: >-
            Takk for tilbakemeldingen!
        - icon: material/emoticon-sad-outline
          name: Siden kan forbedres
          data: 0
          note: >-  # Migrate to fider.io
            Takk for tilbakemeldingen! Hjelp oss bli bedre ved å
            benytte vårt <a href="https://github.com/VaagenIM/docs.iktim.no/issues" target="_blank" rel="noopener">tilbakemeldingsskjema</a>.
  consent:
    title: Samtykke til informasjonskapsler
    actions:
      - accept
      - reject
      - manage 
    description: >- 
      Vi bruker informasjonskapsler for å gjenkjenne dine gjentatte besøk og preferanser, 
      samt for å måle effektiviteten til innholdet og om brukerne finner det de leter etter. 
      Med ditt samtykke hjelper du oss forbedre innholdet på siden.


markdown_extensions:
  # Essentials
  - meta                        # Load frontmatter (---\ntitle: Title\n---
  - attr_list                   # Add HTML attributes to anything (![image](link) { align=left })
  - nl2br                       # All linebreaks add <br> tags (starts new line on new lines...)
  - mdx_breakless_lists         # single linebreak required for lists, instead of two
  - pymdownx.magiclink          # Automatically wrap links to <a> tags https://google.com = <a href="https://google.com">https://google.com</a>

  # Features
  - footnotes                   # Citations (Zotero/Pandoc) ([^1], [^1]: Lorem ipsum)
  - admonition                  # Callout blocks > [!INFO], > [!WARNING], > [!VIDEO], > [!TECH], > [!CODE] (alt: !!! type)  
  - pymdownx.details            # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  - pymdownx.tasklist:          # - [ ] Task, - [x] Task completed
      custom_checkbox: true         # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists

  # Code highlighting
  - pymdownx.superfences        # Code higlighting ```language\n code\n ```
  - pymdownx.highlight:         # Syntax highlighting + superfences
      linenums: true                # numbered lines
      anchor_linenums: true         # generate anchor links to line number
  - pymdownx.inlinehilite       # Inline code highlighting
  # Math / Formulas

  - pymdownx.arithmatex:        # Mathematical formulas $f(a)=f(b)$ $5*2=10$
      generic: true             # Clean formatting for non-MathJax libraries

  # ^~= modifiers
  - pymdownx.caret              # ^^underline^^, ^superscript^ (H^2^O)
  - pymdownx.tilde              # ~~strikethrough~~, ~subscript~ (~2~OH)
  - pymdownx.mark               # ==mark text== (yellow marker)
  - pymdownx.betterem:          # **bold** *italic*, __bold__ _italic_ 
      smart_enable: all             # Both modifiers (* and _)

  # Extra
  - pymdownx.keys               # ++ctrl+alt+delete++ 
  - pymdownx.smartsymbols       # Convert special characters from markdown ((tm) = ™)
  - smarty                      # '' -> ‘’, "" -> “”, etc..
  - pymdownx.emoji:             # Emojis :smile: :tada:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Abbreviations
  - abbr
  - pymdownx.snippets:
      auto_append:
        - references/abbr.md

plugins:
    - search                        # Search bar
    - google-translate:             # Relative paths for google translate
        url: 'docs.iktim.no'
    - tags                          # Searchable tags
    - callouts                      # Convert obsidian callouts to markdown format
    - roamlinks                     # Use WikiLinks
    - glightbox:                    # Lightbox! https://github.com/blueswen/mkdocs-glightbox
    - footermatter:                 # Last edited, date created, author links. Needs to be updated for proper author rendering
        default_author_img: https://ui-avatars.com
        default_author_url: https://github.com/VaagenIM/docs.iktim.no
        date_format: 'timeago'
        locale: 'nb_NO'
        author_map:                 # Name in frontmatter | path RELATIVE TO: resources/assets/authors or URL | website
#          - Sondre Grønås | sondregronas.png | https://github.com/sondregronas
          - Sondre Grønås | https://www.gravatar.com/avatar/4e0476393c848aef61ed66d404da0d14?s=250 | https://github.com/sondregronas
    - bibtex:                       # Citations & reference management (Zotero)
        bib_dir: "references"
        csl_file: "references/harvard-cite-them-right.xml"
        cite_inline: True
    - include_dir_to_nav            # Automatically generate nav: (show directories and pages in sidebar)
    - exclude:                      # Exclude pattern from site
        glob:
          - .obsidian/*
          - _DATA/*
        regex:
          - '.*\.(tmp|bin|tar)$'
    - minify:                       # Optimize load times
        minify_html: true
    - submodule-edit-uri:           # Edit_uri in submodules
        modules:
        - IKT:
            old: https://github.com/VaagenIM/docs.iktim.no/edit/main/docs/IKT
            new: https://github.com/VaagenIM/docs.iktim.no-IKT/edit/main
        - MP:
            old: https://github.com/VaagenIM/docs.iktim.no/edit/main/docs/MP
            new: https://github.com/VaagenIM/docs.iktim.no-MP/edit/main
        - 2022:
            old: https://github.com/VaagenIM/docs.iktim.no/edit/main/docs/2022
            new: https://github.com/VaagenIM/docs.iktim.no-2022/edit/main
