name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  repository_dispatch:
    types: [doc_update]
  schedule:
    - cron:  '0 0 * * *'
    
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
        
    - name: Commit update
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "😄 Updated Docs" && git push || echo "No changes to commit"

    - name: Set Timezone to Europe/Oslo
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Oslo"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt

    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: "2.14.0.3"

    - name: Format spaces
      run: find docs/ -name "* *" -print0 | sort -rz | while read -d $'\0' f; do mv -v "$f" "$(dirname "$f")/$(basename "${f// /-}")"; done

    - name: Build site
      run: |
        echo 'docs.iktim.no' > ./docs/CNAME
        mkdocs build --clean

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: github-pages
        path: ./site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
