name: CD

on:
  push:
    branches: [ main ]

env:
  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Format spaces
      run: |
        echo sudo apt-get install rename
        echo find docs/ -execdir rename 's/ /-/g' '{}' \+
        find docs/ -execdir bash -c 'file={}; git mv "$file" "${file/\ /-}"' \;
        find docs/ -name "* *" -print0 | sort -rz | while read -d $'\0' f; do git mv -v "$f" "$(dirname "$f")/$(basename "${f// /-}")"; done

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: r-lib/actions/setup-pandoc@master
      with:
        pandoc-version: "2.14.0.3"
       
    - name: Deploy
      run: |
        echo 'docs.iktim.no' > ./docs/CNAME
        mkdocs gh-deploy --clean --force