name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: r-lib/actions/setup-pandoc@master
      with:
        pandoc-version: "2.14.0.3"
        
    - name: Format spaces
      run: |
        sudo apt-get install rename
        find docs/ -type d -name "*" | while read f; do echo "'y/ /-/' $f"; done
        find docs/ -type f -name "*.md" | while read f; do rename 'y/ /-/' $f; done

    - name: Deploy
      run: |
        echo 'docs.iktim.no' > ./docs/CNAME
        mkdocs gh-deploy --clean --force