name: CI

# Sjekk at plug-ins fremdeles virker som de skal,
# hvis ikke: varsle på mail.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Pandoc
      run: |
        apt-get update
        apt-get install -y --no-install-recommends pandoc pandoc-citeproc
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test build
      run: |
        mkdocs build -q
